/**
 * render.ts — turn Evidence into a WHOAMI.md scaffold.
 *
 * Two zones, and the ordering is the whole philosophy:
 *   ASSERTED  — the human writes it; it is the source of truth.
 *   OBSERVED  — machine-gathered evidence; explicitly labeled as exposure-only
 *               and undercounting. It informs the ASSERTED section; it never
 *               overrides it.
 */

import type { Evidence } from "./evidence.ts";

const ASSERTED_TEMPLATE = `## ASSERTED — written by me; this is the source of truth

<!-- This section wins over everything below. You are the authority on your own
     expertise. Edit freely; the generator never touches this block. -->

- **Role / level:** 
- **Years in the field:** 
- **Domains of real depth:** 
- **Things I've shipped that GitHub can't see:** 
- **How I think / how to work with me:** 
- **Relevant context (optional):** 
`;

function langTable(ev: Evidence): string {
  if (ev.languages.length === 0) return "_No language data gathered._\n";
  const top = ev.languages.slice(0, 10);
  const rows = top
    .map((l) => `- **${l.language}** — ${l.pct}% of public bytes · ${l.repoCount} repo(s) · last ${l.lastSeen || "?"}`)
    .join("\n");
  return rows + "\n";
}

function disciplineList(ev: Evidence): string {
  if (ev.disciplines.length === 0) return "_No discipline signals detected._\n";
  return (
    ev.disciplines
      .map((d) => `- **${d.tag}** — evidence: ${d.evidence.join(", ") || "—"}`)
      .join("\n") + "\n"
  );
}

function notableList(ev: Evidence): string {
  if (ev.notable.length === 0) return "_No repos._\n";
  return (
    ev.notable
      .map((r) => {
        const star = r.stars ? ` ★${r.stars}` : "";
        const desc = r.description ? ` — ${r.description}` : "";
        return `- [${r.name}](https://github.com/${r.fullName})${star}${desc}`;
      })
      .join("\n") + "\n"
  );
}

export function renderWhoami(ev: Evidence, existingAsserted?: string): string {
  const asserted = existingAsserted?.trim() || ASSERTED_TEMPLATE;
  const date = ev.generatedAt.slice(0, 10);

  return `# WHOAMI

> Portable, user-owned context (a \`CLAUDE.md\` for *who you are*, not the project).
> Drop it where your tools read project context, or paste the ASSERTED block into
> any chat. It exists to start sessions calibrated — so neither side burns turns
> re-establishing who you are.

${asserted}
---

## OBSERVED — public GitHub evidence (generated ${date})

> ⚠️ **Read this as evidence, not as a verdict.** These numbers measure
> *exposure*, not *skill*. Byte counts are inflated by vendored and generated
> code, and **private/employer work is entirely absent** — so for a senior
> engineer this section will undercount real depth. Use it to jog the ASSERTED
> section above; do not let it speak for you.

**Source:** \`${ev.user}\` · ${ev.reposConsidered} repo(s) considered ` +
    `(skipped ${ev.reposSkipped.forks} fork(s), ${ev.reposSkipped.archived} archived)` +
    `${ev.unauthenticated ? " · _public-only, no token — more undercounting_" : ""}

### Language exposure (by attributed public bytes)
${langTable(ev)}
### Discipline signals (exposure, with the evidence that triggered each)
${disciplineList(ev)}
### Notable public repos
${notableList(ev)}
---
_Generated by \`whoami\`. Regenerate any time; your ASSERTED block is preserved._
`;
}

/** Split an existing WHOAMI.md to preserve the human-authored ASSERTED block. */
export function extractAsserted(markdown: string): string | undefined {
  const start = markdown.indexOf("## ASSERTED");
  if (start === -1) return undefined;
  const end = markdown.indexOf("\n---", start);
  return markdown.slice(start, end === -1 ? undefined : end).trim();
}
